WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/core/conv2d_ws.py:40: The name tf.layers.Layer is deprecated. Please use tf.compat.v1.layers.Layer instead.

WARNING:tensorflow:From vis.py:327: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From vis.py:195: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0418 12:34:42.090793 139828207019776 module_wrapper.py:139] From vis.py:195: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From vis.py:195: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0418 12:34:42.090951 139828207019776 module_wrapper.py:139] From vis.py:195: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From vis.py:214: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

W0418 12:34:42.091128 139828207019776 module_wrapper.py:139] From vis.py:214: The name tf.logging.info is deprecated. Please use tf.compat.v1.logging.info instead.

INFO:tensorflow:Cityscapes requires converting train_id to eval_id.
I0418 12:34:42.091203 139828207019776 vis.py:214] Cityscapes requires converting train_id to eval_id.
WARNING:tensorflow:From vis.py:218: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

W0418 12:34:42.091304 139828207019776 module_wrapper.py:139] From vis.py:218: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

INFO:tensorflow:Visualizing on val_fine set
I0418 12:34:42.091568 139828207019776 vis.py:225] Visualizing on val_fine set
WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/datasets/data_generator.py:350: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

W0418 12:34:42.092269 139828207019776 module_wrapper.py:139] From /home/grupo01/tensorflow/models/research/deeplab/datasets/data_generator.py:350: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

WARNING:tensorflow:From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

W0418 12:34:42.228208 139828207019776 module_wrapper.py:139] From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

WARNING:tensorflow:From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.

W0418 12:34:42.229062 139828207019776 module_wrapper.py:139] From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/autograph/converters/directives.py:119: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.

2020-04-18 12:34:42.658447: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-04-18 12:34:42.738978: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:05:00.0
2020-04-18 12:34:42.739234: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-18 12:34:42.740693: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-18 12:34:42.742069: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-04-18 12:34:42.742391: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-04-18 12:34:42.744255: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-04-18 12:34:42.745781: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-04-18 12:34:42.749668: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-18 12:34:42.756731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/datasets/data_generator.py:339: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.
W0418 12:34:44.665639 139828207019776 deprecation.py:323] From /home/grupo01/tensorflow/models/research/deeplab/datasets/data_generator.py:339: DatasetV1.make_one_shot_iterator (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `for ... in dataset:` to iterate over a dataset. If using `tf.estimator`, return the `Dataset` object directly from your input function. As a last resort, you can use `tf.compat.v1.data.make_one_shot_iterator(dataset)`.
INFO:tensorflow:Performing single-scale test.
I0418 12:34:44.683679 139828207019776 vis.py:237] Performing single-scale test.
WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/model.py:320: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

W0418 12:34:44.683911 139828207019776 module_wrapper.py:139] From /home/grupo01/tensorflow/models/research/deeplab/model.py:320: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/core/feature_extractor.py:490: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
W0418 12:34:44.684410 139828207019776 deprecation.py:323] From /home/grupo01/tensorflow/models/research/deeplab/core/feature_extractor.py:490: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/core/xception.py:469: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0418 12:34:44.686488 139828207019776 module_wrapper.py:139] From /home/grupo01/tensorflow/models/research/deeplab/core/xception.py:469: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

WARNING:tensorflow:From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
W0418 12:34:44.689148 139828207019776 deprecation.py:323] From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/grupo01/tensorflow/models/research/deeplab/core/utils.py:41: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

W0418 12:34:48.784338 139828207019776 module_wrapper.py:139] From /home/grupo01/tensorflow/models/research/deeplab/core/utils.py:41: The name tf.image.resize_bilinear is deprecated. Please use tf.compat.v1.image.resize_bilinear instead.

WARNING:tensorflow:From vis.py:276: The name tf.train.get_or_create_global_step is deprecated. Please use tf.compat.v1.train.get_or_create_global_step instead.

W0418 12:34:48.919234 139828207019776 module_wrapper.py:139] From vis.py:276: The name tf.train.get_or_create_global_step is deprecated. Please use tf.compat.v1.train.get_or_create_global_step instead.

INFO:tensorflow:Waiting for new checkpoint at ./datasets/cityscapes/exp/train_on_train_set/train/exp3
I0418 12:34:48.922455 139828207019776 evaluation.py:189] Waiting for new checkpoint at ./datasets/cityscapes/exp/train_on_train_set/train/exp3
INFO:tensorflow:Found new checkpoint at ./datasets/cityscapes/exp/train_on_train_set/train/exp3/model.ckpt-14357
I0418 12:34:48.925400 139828207019776 evaluation.py:198] Found new checkpoint at ./datasets/cityscapes/exp/train_on_train_set/train/exp3/model.ckpt-14357
INFO:tensorflow:Starting visualization at 2020-04-18-10:34:48
I0418 12:34:48.925781 139828207019776 vis.py:289] Starting visualization at 2020-04-18-10:34:48
INFO:tensorflow:Visualizing with model ./datasets/cityscapes/exp/train_on_train_set/train/exp3/model.ckpt-14357
I0418 12:34:48.925922 139828207019776 vis.py:290] Visualizing with model ./datasets/cityscapes/exp/train_on_train_set/train/exp3/model.ckpt-14357
WARNING:tensorflow:From vis.py:292: The name tf.train.Scaffold is deprecated. Please use tf.compat.v1.train.Scaffold instead.

W0418 12:34:48.926224 139828207019776 module_wrapper.py:139] From vis.py:292: The name tf.train.Scaffold is deprecated. Please use tf.compat.v1.train.Scaffold instead.

WARNING:tensorflow:From vis.py:292: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

W0418 12:34:48.926451 139828207019776 module_wrapper.py:139] From vis.py:292: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

WARNING:tensorflow:From vis.py:293: The name tf.train.ChiefSessionCreator is deprecated. Please use tf.compat.v1.train.ChiefSessionCreator instead.

W0418 12:34:48.947982 139828207019776 module_wrapper.py:139] From vis.py:293: The name tf.train.ChiefSessionCreator is deprecated. Please use tf.compat.v1.train.ChiefSessionCreator instead.

WARNING:tensorflow:From vis.py:297: The name tf.train.MonitoredSession is deprecated. Please use tf.compat.v1.train.MonitoredSession instead.

W0418 12:34:48.948307 139828207019776 module_wrapper.py:139] From vis.py:297: The name tf.train.MonitoredSession is deprecated. Please use tf.compat.v1.train.MonitoredSession instead.

WARNING:tensorflow:From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0418 12:34:49.573513 139828207019776 deprecation.py:323] From /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/array_ops.py:1475: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO:tensorflow:Graph was finalized.
I0418 12:34:50.608885 139828207019776 monitored_session.py:240] Graph was finalized.
2020-04-18 12:34:50.609633: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-18 12:34:50.628132: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099885000 Hz
2020-04-18 12:34:50.629410: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55aa007b42a0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-18 12:34:50.629434: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-18 12:34:50.890926: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55aa007b69d0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-04-18 12:34:50.890969: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN X (Pascal), Compute Capability 6.1
2020-04-18 12:34:50.894110: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: TITAN X (Pascal) major: 6 minor: 1 memoryClockRate(GHz): 1.531
pciBusID: 0000:05:00.0
2020-04-18 12:34:50.894218: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-18 12:34:50.894248: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-18 12:34:50.894272: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-04-18 12:34:50.894295: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-04-18 12:34:50.894316: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-04-18 12:34:50.894341: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-04-18 12:34:50.894366: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-18 12:34:50.900342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-04-18 12:34:50.901223: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-04-18 12:34:50.908833: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-18 12:34:50.908856: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-04-18 12:34:50.908864: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-04-18 12:34:50.915896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 11448 MB memory) -> physical GPU (device: 0, name: TITAN X (Pascal), pci bus id: 0000:05:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from ./datasets/cityscapes/exp/train_on_train_set/train/exp3/model.ckpt-14357
I0418 12:34:50.918420 139828207019776 saver.py:1284] Restoring parameters from ./datasets/cityscapes/exp/train_on_train_set/train/exp3/model.ckpt-14357
INFO:tensorflow:Running local_init_op.
I0418 12:35:17.052723 139828207019776 session_manager.py:500] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0418 12:35:17.254060 139828207019776 session_manager.py:502] Done running local_init_op.
INFO:tensorflow:Visualizing batch 1
I0418 12:35:18.501915 139828207019776 vis.py:303] Visualizing batch 1
2020-04-18 12:35:28.412732: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-04-18 12:35:39.602481: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-04-18 12:35:49.794205: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at spacetobatch_op.cc:219 : Invalid argument: padded_shape[0]=69 is not divisible by block_shape[0]=2
Traceback (most recent call last):
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: padded_shape[0]=69 is not divisible by block_shape[0]=2
	 [[{{node xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND}}]]
	 [[ArgMax/_4373]]
  (1) Invalid argument: padded_shape[0]=69 is not divisible by block_shape[0]=2
	 [[{{node xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vis.py", line 327, in <module>
    tf.app.run()
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "vis.py", line 313, in main
    train_id_to_eval_id=train_id_to_eval_id)
  File "vis.py", line 161, in _process_batch
    image_names, image_heights, image_widths])
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1259, in run
    run_metadata=run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1360, in run
    raise six.reraise(*original_exc_info)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1345, in run
    return self._sess.run(*args, **kwargs)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1418, in run
    run_metadata=run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/training/monitored_session.py", line 1176, in run
    return self._sess.run(*args, **kwargs)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: padded_shape[0]=69 is not divisible by block_shape[0]=2
	 [[node xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND (defined at /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[ArgMax/_4373]]
  (1) Invalid argument: padded_shape[0]=69 is not divisible by block_shape[0]=2
	 [[node xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND (defined at /home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'xception_65/exit_flow/block2/unit_1/xception_module/separable_conv1_depthwise/depthwise/SpaceToBatchND':
  File "vis.py", line 327, in <module>
    tf.app.run()
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "vis.py", line 241, in main
    image_pyramid=FLAGS.image_pyramid)
  File "/home/grupo01/tensorflow/models/research/deeplab/model.py", line 188, in predict_labels
    fine_tune_batch_norm=False)
  File "/home/grupo01/tensorflow/models/research/deeplab/model.py", line 323, in multi_scale_logits
    nas_training_hyper_parameters=nas_training_hyper_parameters)
  File "/home/grupo01/tensorflow/models/research/deeplab/model.py", line 577, in _get_logits
    nas_training_hyper_parameters=nas_training_hyper_parameters)
  File "/home/grupo01/tensorflow/models/research/deeplab/model.py", line 404, in extract_features
    use_bounded_activation=model_options.use_bounded_activation)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/feature_extractor.py", line 643, in extract_features
    scope=name_scope[model_variant])
  File "/home/grupo01/tensorflow/models/research/deeplab/core/feature_extractor.py", line 710, in network_fn
    *args, **kwargs)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 744, in xception_65
    sync_batch_norm_method=sync_batch_norm_method)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 716, in xception_65_factory
    sync_batch_norm_method=sync_batch_norm_method)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 491, in xception
    net = stack_blocks_dense(net, blocks, output_stride)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 402, in stack_blocks_dense
    net = block.unit_fn(net, rate=rate, **dict(unit, stride=1))
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 308, in xception_module
    scope='separable_conv' + str(i+1))
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 299, in _separable_conv
    scope=scope)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 194, in separable_conv2d_same
    outputs = _split_separable_conv2d(padding='SAME')
  File "/home/grupo01/tensorflow/models/research/deeplab/core/xception.py", line 184, in _split_separable_conv2d
    **kwargs)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py", line 2827, in separable_convolution2d
    data_format=data_format)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_impl.py", line 819, in depthwise_conv2d
    op=op)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 483, in with_space_to_batch
    return new_op(input, None)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 639, in __call__
    return self.call(inp, filter)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/nn_ops.py", line 622, in _with_space_to_batch_call
    input=inp, block_shape=dilation_rate, paddings=paddings)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 9652, in space_to_batch_nd
    paddings=paddings, name=name)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/grupo01/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

